apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: lesson-
build:
  artifacts:
  - image: my-cool-app
    context: src
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
